
server:
  port: 9091

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/drone?serverTimezone=GMT%2b8
    username: root
    password: mima3839
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB/**
mybatis:
  mapper-locations: classpath:Mapper/*.xml #扫描所有mybatis文件

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


